# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: '쇼핑',                url: 'shopping'}
- {name: '인사말',               url: 'about'}
- {name: '리뷰',                url: 'review'}
- {name: '이벤트',               url: 'offer'}
- {name: '문의',                url: 'contact'}
- {name: '공지사항',             url: 'notice'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://www.instagram.com/wooriwalkincloset'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
